source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
gem 'unicorn'

gem 'dotenv-rails'
gem 'devise', '4.5.0' #ユーザ認証
gem 'omniauth-twitter' #twitter認証
gem 'omniauth-facebook' #facebook認証
gem 'omniauth-instagram' #insta認証
gem 'omniauth-google-oauth2' #google認証
gem 'omniauth-line' #line認証
gem 'kaminari' #スマートなページングを作ってくれる
#gem 'gmaps4rails' #google map
#gem 'geocoder' #ジオコーダ。緯度経度を住所に変換したり住所を緯度経度に変換できる。
gem 'font-awesome-rails' #綺麗なアイコンが描ける
gem 'twitter-bootswatch-rails' #bootstrapのテーマ
gem 'twitter-bootswatch-rails-helpers' #bootstrapのテーマ
gem 'less-rails' #bootstrapをコンパイルするのに必要
gem 'sassc-rails' #bootstrapをコンパイルするのに必要
gem 'jquery-rails' #jquery　これがないと始まらない。　ほぼ必須のgemだ
gem 'photoswipe-rails' #画像をライトボックス表示できる
gem 'cropper-rails' #画像をアップロードするときに好きな矩形でトリミングできる
#gem 'c3-rails' #キレイなグラフを描ける
#gem 'd3-rails', '~> 3.5.17' #キレイなグラフを描ける
gem 'ransack' #複雑な条件でのDB検索を、直感的なメソッドで書ける
gem 'simple_form' #入力フォームをシンプルに書ける。ほぼ必須。
gem 'counter_culture' #has_manyの関係にあるオブジェクトの数を数えることができる
#gem 'layzr-rails' #画像の遅延ロードができる。しかしSEO的には弱いと言われている。
#gem 'recaptcha', require: 'recaptcha/rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'therubyracer', platforms: :ruby
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Use Puma as the app server
  gem 'puma', '~> 3.11'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

